---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: default
  
data:
  MONGO_URL: mongodb://mongo:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testeinfra-deployment
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: testeinfra
  template:
    metadata:
      labels:
        app: testeinfra
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: app
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 3000
          #envFrom:
          #- configMapRef:
          #  name: mongo-config
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
          #imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: testeinfra-service
  namespace: default
spec:
  selector:
    app: testeinfra
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testeinfra-ingress
  namespace: default
spec:
  rules:
  - host: testeinfra.clustersoft.robertotrevisan.com.br
    http:
      paths:
      - backend:
          serviceName: testeinfra-service
          servicePort: 80
status:
  loadBalancer: {}